ITEM.name = "Тестовая коробка боеприпасов"
ITEM.description = "Тестовый предмет для проверки выдачи кастомных патронов. Поменяй ammoType после проверки через /DebugAmmo."
ITEM.base = "base_ammo"
ITEM.model = "models/items/boxmrounds.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Ammo"
ITEM.ammoType = "Pistol"
ITEM.ammoAmount = 30
ITEM.ammoBoxText = "Используй /DebugAmmo, посмотри Primary ammo name у нужного оружия и впиши его сюда в ammoType."
