ix.randomitems = ix.randomitems or {}
ix.randomitems.tables = ix.randomitems.tables or {}

--[[
    reward_stalker_loot.lua v2
    - дешёвый хабар и простые ингредиенты выпадают чаще;
    - еда выпадает умеренно часто;
    - медицина падает чуть реже;
    - дорогой хабар и инструменты заметно реже;
    - квестовые предметы убраны из контейнерного лута;
    - chemical_reagent оставлен редким.
]]

ix.randomitems.tables["loot_mixed_low"] = {
    {4400, {"glue"}},
    {4300, {"fire_fuel"}},
    {4200, {"ducktape"}},
    {4100, {"lottery_ticket"}},
    {3900, {"firestarter_tinder"}},
    {3700, {"kucocktkani"}},
    {3500, {"copper_wire"}},
    {3400, {"soviet_money"}},
    {3200, {"rope"}},
    {3000, {"boxtabak"}},
    {2700, {"rastrrovitel"}},
    {2450, {"kalnifyli"}},
    {2300, {"braka"}},
    {2100, {"chain"}},
    {1850, {"transistor"}},
    {1700, {"controller"}},
    {1500, {"hdd"}},
    {1300, {"cat_figurine"}},
    {1150, {"chemical_reagent"}},
    {980, {"car_battery"}},
    {920, {"polaroid"}},
    {860, {"salt"}},
    {840, {"flour"}},
    {820, {"garlic"}},
    {760, {"mukhomor"}},
    {720, {"edible_mushroom"}},
    {680, {"food_galets"}},
    {620, {"food_can_beans_custom"}},
    {560, {"food_condensed_milk"}},
    {520, {"drink_beer_flask"}},
    {460, {"cig_dolb"}},
    {340, {"cig_balboro"}},
    {300, {"repairkit1"}},
    {220, {"gasmask_filter"}},
    {180, {"armor_scraps"}},
    {120, {"book"}},
    {85, {"document_case1"}},
    {55, {"medic_iodine"}},
    {35, {"medic_bandagepack"}},
}

ix.randomitems.tables["loot_mixed_mid"] = {
    {3100, {"boxtabak"}},
    {2950, {"rope"}},
    {2800, {"soviet_money"}},
    {2600, {"polaroid"}},
    {2400, {"firestarter_tinder"}},
    {2300, {"fire_fuel"}},
    {2200, {"glue"}},
    {2100, {"ducktape"}},
    {2000, {"kucocktkani"}},
    {1800, {"chain"}},
    {1650, {"copper_wire"}},
    {1500, {"textolite"}},
    {1450, {"rastrrovitel"}},
    {1320, {"cat_figurine"}},
    {1250, {"hdd"}},
    {1180, {"coin_purse"}},
    {1120, {"data_disc"}},
    {1040, {"broken_dosimeter"}},
    {980, {"controller"}},
    {940, {"car_battery"}},
    {900, {"circuit_board"}},
    {840, {"weapon_parts"}},
    {800, {"portablebed"}},
    {760, {"gasmask_filter"}},
    {720, {"hand_lamp"}},
    {680, {"drink_beer_flask"}},
    {650, {"food_can_beans_custom"}},
    {620, {"food_condensed_milk"}},
    {590, {"food_galets"}},
    {560, {"garlic"}},
    {540, {"salt"}},
    {520, {"flour"}},
    {500, {"edible_mushroom"}},
    {420, {"mukhomor"}},
    {380, {"cig_dolb"}},
    {300, {"cig_balboro"}},
    {260, {"repairkit1"}},
    {220, {"gun_maslo"}},
    {190, {"chemical_reagent"}},
    {170, {"book"}},
    {150, {"wick_docs02"}},
    {120, {"document_case1"}},
    {95, {"document_case2"}},
    {70, {"medic_iodine"}},
    {55, {"medic_vicasol"}},
    {45, {"medic_bandagepack"}},

    -- Редкие детали уникального оружия: без самих оружий.
    {70, {"northern_long_pipe_barrel"}},
    {55, {"northern_homemade_lock"}},
}

ix.randomitems.tables["loot_mixed_high"] = {
    {2100, {"usd_money"}},
    {2000, {"soviet_money"}},
    {1900, {"polaroid"}},
    {1800, {"pocket_radio"}},
    {1600, {"portable_radio"}},
    {1500, {"book"}},
    {1420, {"coin_purse"}},
    {1360, {"data_disc"}},
    {1280, {"horse_figurine"}},
    {1220, {"gold_chain"}},
    {1150, {"broken_dosimeter"}},
    {1080, {"portablebed"}},
    {1020, {"gasmask_filter"}},
    {980, {"weapon_parts"}},
    {920, {"armor_scraps"}},
    {860, {"small_engine"}},
    {780, {"gasoline_can"}},
    {720, {"chemical_reagent"}},
    {660, {"armor_plate"}},
    {620, {"multiknife"}},
    {560, {"multitool"}},
    {460, {"weapon_clearkit"}},
    {420, {"lockpicks"}},
    {360, {"document_case1"}},
    {300, {"document_case2"}},
    {250, {"writing_book1"}},
    {220, {"wick_docs02"}},
    {180, {"document_case3"}},
    {150, {"scoutdoc"}},
    {130, {"writing_book2"}},
    {110, {"toolkit_rough"}},
    {90, {"toolkit_fine"}},
    {70, {"toolkit_calib"}},
    {55, {"military_battery"}},
    {35, {"gold_ingot"}},
    {24, {"medic_iodine"}},
    {18, {"medic_vicasol"}},
    {14, {"medic_bandagepack"}},

    -- Редкие чертежи уникального оружия: падают очень редко.
    {95, {"northern_long_pipe_barrel"}},
    {80, {"northern_homemade_lock"}},
    {42, {"mp18_old_receiver"}},
    {36, {"mp18_snail_mag"}},
    {28, {"volks_rough_receiver"}},
    {24, {"volks_bolt_group"}},
    {16, {"nock_reinforced_stock"}},
    {10, {"nock_seven_barrel_block"}},
    {14, {"note_blueprint_northern_nail"}},
    {10, {"note_blueprint_mp18_okopnik"}},
    {7, {"note_blueprint_volks_last_line"}},
    {4, {"note_blueprint_nock_gromoboy"}},
}

ix.randomitems.tables["loot_civilian"] = {
    {3400, {"boxtabak"}},
    {3200, {"soviet_money"}},
    {3000, {"polaroid"}},
    {2800, {"book"}},
    {2600, {"lottery_ticket"}},
    {2300, {"rope"}},
    {2100, {"cat_figurine"}},
    {1800, {"coin_purse"}},
    {1650, {"food_condensed_milk"}},
    {1500, {"food_galets"}},
    {1450, {"chocolate_alenka"}},
    {1300, {"cig_dolb"}},
    {1100, {"pocket_radio"}},
    {980, {"writing_book1"}},
    {900, {"portable_radio"}},
    {760, {"document_case1"}},
    {650, {"cig_balboro"}},
    {540, {"wick_docs02"}},
    {420, {"writing_book2"}},
    {360, {"document_case2"}},
    {250, {"document_case3"}},
    {180, {"scoutdoc"}},
}

ix.randomitems.tables["loot_survival"] = {
    {3300, {"rope"}},
    {3200, {"kucocktkani"}},
    {3000, {"firestarter_tinder"}},
    {2800, {"fire_fuel"}},
    {2350, {"portablebed"}},
    {2200, {"gasmask_filter"}},
    {2050, {"hand_lamp"}},
    {1800, {"drink_water_gurzhomi"}},
    {1650, {"food_baton"}},
    {1500, {"food_galets"}},
    {1450, {"food_can_beans_custom"}},
    {1320, {"food_condensed_milk"}},
    {1200, {"drink_beer_flask"}},
    {1100, {"garlic"}},
    {1000, {"salt"}},
    {950, {"flour"}},
    {900, {"edible_mushroom"}},
    {720, {"mukhomor"}},
    {520, {"repairkit1"}},
    {320, {"medic_iodine"}},
    {220, {"medic_vicasol"}},
    {180, {"medic_bandagepack"}},
    {120, {"chemical_reagent"}},
}

ix.randomitems.tables["loot_tools"] = {
    {2600, {"copper_wire"}},
    {2400, {"textolite"}},
    {2200, {"glue"}},
    {2100, {"ducktape"}},
    {1950, {"gun_maslo"}},
    {1800, {"repairkit1"}},
    {1650, {"kondensatory"}},
    {1450, {"transistor"}},
    {1320, {"controller"}},
    {1200, {"weapon_parts"}},
    {1040, {"armor_scraps"}},
    {980, {"circuit_board"}},
    {920, {"small_engine"}},
    {760, {"multiknife"}},
    {680, {"multitool"}},
    {520, {"weapon_clearkit"}},
    {420, {"lockpicks"}},
    {300, {"armor_plate"}},
    {240, {"gasoline_can"}},
    {180, {"chemical_reagent"}},
    {110, {"toolkit_rough"}},
    {90, {"toolkit_fine"}},
    {70, {"toolkit_calib"}},
    {50, {"military_battery"}},

    -- Редкие детали уникального оружия: без самих оружий.
    {85, {"northern_long_pipe_barrel"}},
    {70, {"northern_homemade_lock"}},
    {45, {"mp18_old_receiver"}},
    {38, {"mp18_snail_mag"}},
    {30, {"volks_rough_receiver"}},
    {26, {"volks_bolt_group"}},
    {18, {"nock_reinforced_stock"}},
    {12, {"nock_seven_barrel_block"}},
}

ix.randomitems.tables["loot_documents"] = {
    {2400, {"document_case1"}},
    {2200, {"book"}},
    {1900, {"wick_docs02"}},
    {1750, {"writing_book1"}},
    {1500, {"scoutdoc"}},
    {1320, {"document_case2"}},
    {1080, {"writing_book2"}},
    {860, {"document_case3"}},

    -- Редкие чертежи уникального оружия: падают очень редко.
    {22, {"note_blueprint_northern_nail"}},
    {16, {"note_blueprint_mp18_okopnik"}},
    {10, {"note_blueprint_volks_last_line"}},
    {6, {"note_blueprint_nock_gromoboy"}},
}

ix.randomitems.tables["ix_entbox_drops"] = {
    {3600, {"glue"}},
    {3500, {"fire_fuel"}},
    {3400, {"ducktape"}},
    {3300, {"firestarter_tinder"}},
    {3200, {"kucocktkani"}},
    {3000, {"copper_wire"}},
    {2800, {"boxtabak"}},
    {2600, {"soviet_money"}},
    {2400, {"rope"}},
    {2200, {"rastrrovitel"}},
    {2050, {"salt"}},
    {1950, {"flour"}},
    {1850, {"garlic"}},
    {1750, {"edible_mushroom"}},
    {1650, {"mukhomor"}},
    {1500, {"food_galets"}},
    {1400, {"food_can_beans_custom"}},
    {1300, {"food_condensed_milk"}},
    {1200, {"drink_beer_flask"}},
    {1100, {"cig_dolb"}},
    {950, {"chemical_reagent"}},
    {820, {"chain"}},
    {720, {"textolite"}},
    {620, {"polaroid"}},
    {560, {"cat_figurine"}},
    {480, {"gasmask_filter"}},
    {360, {"repairkit1"}},
    {280, {"armor_scraps"}},
    {220, {"multitool"}},
    {180, {"weapon_parts"}},
    {140, {"document_case1"}},
    {90, {"document_case2"}},
    {60, {"armor_plate"}},
    {40, {"medic_iodine"}},
    {28, {"medic_bandagepack"}},

    -- Очень редкие детали/чертежи уникального оружия для ломаемых ящиков.
    {55, {"northern_long_pipe_barrel"}},
    {42, {"northern_homemade_lock"}},
    {22, {"mp18_old_receiver"}},
    {18, {"mp18_snail_mag"}},
    {14, {"volks_rough_receiver"}},
    {12, {"volks_bolt_group"}},
    {8, {"nock_reinforced_stock"}},
    {5, {"nock_seven_barrel_block"}},
    {6, {"note_blueprint_northern_nail"}},
    {4, {"note_blueprint_mp18_okopnik"}},
    {3, {"note_blueprint_volks_last_line"}},
    {2, {"note_blueprint_nock_gromoboy"}},
}

-- Отдельная редкая группа: детали уникального оружейного крафта.
-- Можно указать как CustomSpawngroup = "loot_unique_weapon_parts" у ящика/контейнера.
ix.randomitems.tables["loot_unique_weapon_parts"] = {
    {1800, {"weapon_parts"}},
    {1200, {"weapon_clearkit"}},
    {900, {"multitool"}},
    {760, {"military_battery"}},
    {520, {"northern_long_pipe_barrel"}},
    {430, {"northern_homemade_lock"}},
    {260, {"mp18_old_receiver"}},
    {220, {"mp18_snail_mag"}},
    {170, {"volks_rough_receiver"}},
    {150, {"volks_bolt_group"}},
    {90, {"nock_reinforced_stock"}},
    {55, {"nock_seven_barrel_block"}},
}

-- Отдельная сверхредкая группа: только чертежи уникального оружия.
-- Лучше использовать для закрытых сейфов, тайников оружейника или редких контейнеров.
ix.randomitems.tables["loot_unique_weapon_blueprints"] = {
    {1200, {"book"}},
    {900, {"document_case1"}},
    {650, {"writing_book1"}},
    {420, {"wick_docs02"}},
    {120, {"note_blueprint_northern_nail"}},
    {85, {"note_blueprint_mp18_okopnik"}},
    {55, {"note_blueprint_volks_last_line"}},
    {30, {"note_blueprint_nock_gromoboy"}},
}
